// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsrC1JLJ1fdXNtQSceJZT8ptlt2iVhkcs',
    appId: '1:1095789627246:web:25ea9def9e2144685b237f',
    messagingSenderId: '1095789627246',
    projectId: 'zamess-123e5',
    authDomain: 'zamess-123e5.firebaseapp.com',
    storageBucket: 'zamess-123e5.appspot.com',
    measurementId: 'G-68G9LLC3RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQClV8YlNCP4L1pqMFYSHrKrj3Gu0nFBc',
    appId: '1:1095789627246:android:18a2ed10baab67765b237f',
    messagingSenderId: '1095789627246',
    projectId: 'zamess-123e5',
    storageBucket: 'zamess-123e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdDVOLCmTURVYKkyvW5Y3oOTFsH7SDeaE',
    appId: '1:1095789627246:ios:f744e843a90043745b237f',
    messagingSenderId: '1095789627246',
    projectId: 'zamess-123e5',
    storageBucket: 'zamess-123e5.appspot.com',
    iosClientId: '1095789627246-5d25i7ftfhrgkv0ufovrk9js2ejesj8s.apps.googleusercontent.com',
    iosBundleId: 'com.zaymanoff.mesapp',
  );
}
